### ISSUE TITLE
Configurable delay durations

### ISSUE THREAD

**Issue by anisus** [resgateio/resclient#61]
## Issue

It should be possible to configure the duration for delays:

* `reconnectDelay` -  Milliseconds between WebSocket reconnect attempts. Defaults to 3000.
* `subscribeStaleDelay` - Milliseconds until a subscribe attempt is made on a stale resource. Zero means no attempt to subscribe. Defaults to 2000.
* `subscribeRetryDelay` - Milliseconds between subscribe attempts on a stale resource after a failed stale subscribe. Zero means no retries. Defaults to 10000.
* `unsubscribeDelay` - Milliseconds between stopping listening to a resource, and the resource being unsubscribed. Defaults to 5000.

**Comment by jirenius** [comment]
Resolved in PR #62
